# Generated by Django 5.1.5 on 2025-02-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='note',
            field=models.CharField(default='', max_length=100),
        ),
    ]
